packetbeat.interfaces.device: enp0s8

packetbeat.flows:
  timeout: 30s
  period: 10s

packetbeat.protocols.dns:
  ports: [53]
  include_authorities: true
  include_additionals: true

packetbeat.protocols.http:
  ports: [80, 5601, 9200, 8080, 8081, 5000, 8002]

#packetbeat.protocols.memcache:
#  ports: [11211]

#packetbeat.protocols.mysql:
#  ports: [3306]

#packetbeat.protocols.pgsql:
#  ports: [5432]

#packetbeat.protocols.redis:
#  ports: [6379]

#packetbeat.protocols.thrift:
#  ports: [9090]

packetbeat.protocols.mongodb:
  ports: [27017]

#packetbeat.protocols.cassandra:
#  ports: [9042]


processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['127.0.0.1:9200']
#  protocol: "https"
  username: elastic
  # Read PW from packetbeat.keystore
  password: "changeme"
#  ssl.certificate_authorities: ["/usr/share/packetbeat/certs/ca/ca.crt"]

setup.kibana:
  host: "http://127.0.0.1:5601"
  username: elastic
  password: "changeme"
#  protocol: "http"
#  ssl.enabled: false
#  ssl.certificate_authorities: ["/usr/share/packetbeat/certs/ca/ca.crt"]

#xpack.monitoring.enabled: true